---
- hosts: ansible-host
  become: true

  tasks:
    - name: setup private key
      copy:
        src: guidkey.pem
        dest: "/home/vagrant/.ssh/{{ GUID }}key.pem"
        mode: 0400
        owner: vagrant

...
  